#!/usr/bin/env python3
# Generated by tools/bundle_verify.py from gpcanon/ — edit the package, not this file.
from __future__ import annotations

# ---- gpcanon/canon.py ----------------------------------------------------
"""gp-canon/1 value model, strict parser and canonical bytes (CANON §1–3, §6–7). Stdlib only.

The verifier imports this module; it must never gain a third-party dependency.
"""

import hashlib
import json
import math
import unicodedata
from decimal import ROUND_HALF_EVEN, Decimal

CANON_VERSION = "gp-canon/1"
INT_MAX = 2**53 - 1
GENESIS = "0" * 64


class CanonError(ValueError):
    """Raised with one of the CANON §7 reason codes."""

    def __init__(self, reason: str, detail: str = ""):
        super().__init__(f"{reason}: {detail}" if detail else reason)
        self.reason = reason


# ---------- producer side: canonical bytes ------------------------------------------

_ESC = {'"': '\\"', "\\": "\\\\", "\b": "\\b", "\f": "\\f", "\n": "\\n", "\r": "\\r", "\t": "\\t"}


def _check_str(s: str) -> None:
    try:
        s.encode("utf-8")
    except UnicodeEncodeError:
        raise CanonError("lone_surrogate") from None
    if not unicodedata.is_normalized("NFC", s):
        raise CanonError("non_nfc", repr(s[:40]))


def _str(s: str) -> str:
    _check_str(s)
    out = []
    for ch in s:
        e = _ESC.get(ch)
        if e is not None:
            out.append(e)
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _ser(v, out: list) -> None:
    if v is None:
        out.append("null")
    elif v is True:
        out.append("true")
    elif v is False:
        out.append("false")
    elif isinstance(v, int):
        if not -INT_MAX <= v <= INT_MAX:
            raise CanonError("int_range", str(v))
        out.append(str(v))
    elif isinstance(v, float):
        raise CanonError("float", repr(v))
    elif isinstance(v, str):
        out.append(_str(v))
    elif isinstance(v, (list, tuple)):
        out.append("[")
        for i, x in enumerate(v):
            if i:
                out.append(",")
            _ser(x, out)
        out.append("]")
    elif isinstance(v, dict):
        for k in v:
            if not isinstance(k, str):
                raise CanonError("bad_type", f"object key {k!r}")
            _check_str(k)
        out.append("{")
        for i, k in enumerate(sorted(v, key=lambda k: k.encode("utf-8"))):   # code point order
            if i:
                out.append(",")
            out.append(_str(k))
            out.append(":")
            _ser(v[k], out)
        out.append("}")
    else:
        raise CanonError("bad_type", type(v).__name__)


def canon(v) -> bytes:
    out: list[str] = []
    _ser(v, out)
    return "".join(out).encode("utf-8")


def sha256_hex(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def record_hash(sealed: dict) -> str:
    return sha256_hex(canon(sealed))


def digest(v) -> str:
    """'sha256:' + hex of canon(v). Used for inputs_digest."""
    return "sha256:" + sha256_hex(canon(v))


def file_digest(path) -> str:
    with open(path, "rb") as f:
        return "sha256:" + hashlib.sha256(f.read()).hexdigest()


def decimal_from_float(x, places: int) -> str:
    """The one sanctioned float -> decimal-string conversion (CANON §6)."""
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        raise CanonError("bad_type", type(x).__name__)
    if isinstance(x, float) and not math.isfinite(x):
        raise CanonError("non_finite", repr(x))
    if isinstance(places, bool) or not isinstance(places, int) or not 0 <= places <= 18:
        raise CanonError("bad_places", repr(places))
    d = Decimal(repr(x)) if isinstance(x, float) else Decimal(x)
    q = d.quantize(Decimal(1).scaleb(-places), rounding=ROUND_HALF_EVEN)
    if q.is_zero():
        q = q.copy_abs()
    return format(q, "f")


def nfc(v):
    """Producer-boundary normalisation: NFC every string (keys and values), recursively.

    Call this on data you own before handing it to canon(). Verifiers must never call it.
    """
    if isinstance(v, str):
        return unicodedata.normalize("NFC", v)
    if isinstance(v, list):
        return [nfc(x) for x in v]
    if isinstance(v, dict):
        return {unicodedata.normalize("NFC", k): nfc(x) for k, x in v.items()}
    return v


# ---------- verifier side: strict parse --------------------------------------------

def _reject_float(s):
    raise CanonError("float", s)


def _parse_int(s: str) -> int:
    if s == "-0":
        raise CanonError("neg_zero")
    n = int(s)
    if not -INT_MAX <= n <= INT_MAX:
        raise CanonError("int_range", s)
    return n


def _reject_constant(s):
    raise CanonError("bad_json", s)


def _pairs(pairs):
    d = {}
    for k, v in pairs:
        if k in d:
            raise CanonError("dup_key", repr(k))
        d[k] = v
    return d


def _walk_strings(v):
    if isinstance(v, str):
        _check_str(v)
    elif isinstance(v, list):
        for x in v:
            _walk_strings(x)
    elif isinstance(v, dict):
        for k, x in v.items():
            _check_str(k)
            _walk_strings(x)


def parse(data: bytes | str):
    """Strict RFC 8259 parse into the gp-canon/1 value model, or CanonError with a CANON §2 reason."""
    if isinstance(data, bytes):
        if data.startswith(b"\xef\xbb\xbf"):
            raise CanonError("bad_json", "BOM")
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as e:
            # UTF-8-encoded surrogates (ED A0..BF xx) are raw lone surrogates; anything else is bad JSON.
            bad = data[e.start:e.start + 2]
            if len(bad) == 2 and bad[0] == 0xED and 0xA0 <= bad[1] <= 0xBF:
                raise CanonError("lone_surrogate") from None
            raise CanonError("bad_json", "invalid UTF-8") from None
    else:
        text = data
        if text.startswith("﻿"):
            raise CanonError("bad_json", "BOM")
    try:
        v = json.loads(text, parse_float=_reject_float, parse_int=_parse_int,
                       parse_constant=_reject_constant, object_pairs_hook=_pairs)
    except CanonError:
        raise
    except (json.JSONDecodeError, RecursionError, ValueError) as e:
        raise CanonError("bad_json", str(e)[:80]) from None
    _walk_strings(v)
    return v

# ---- gpcanon/ed25519_verify.py -------------------------------------------
"""Pure-Python Ed25519 verification (RFC 8032 §5.1.7). Stdlib only.

Verification handles no secrets, so constant-time code is not needed. Signing
is never done here: producers use the `cryptography` package.
"""

import hashlib

P = 2**255 - 19
L = 2**252 + 27742317777372353535851937790883648493
D = (-121665 * pow(121666, P - 2, P)) % P
SQRT_M1 = pow(2, (P - 1) // 4, P)


def _inv(x: int) -> int:
    return pow(x, P - 2, P)


def _add(p, q):
    x1, y1, z1, t1 = p
    x2, y2, z2, t2 = q
    a = (y1 - x1) * (y2 - x2) % P
    b = (y1 + x1) * (y2 + x2) % P
    c = 2 * t1 * t2 * D % P
    d = 2 * z1 * z2 % P
    e, f, g, h = b - a, d - c, d + c, b + a
    return (e * f % P, g * h % P, f * g % P, e * h % P)


def _mul(s: int, p):
    q = (0, 1, 1, 0)
    while s:
        if s & 1:
            q = _add(q, p)
        p = _add(p, p)
        s >>= 1
    return q


def _equal(p, q) -> bool:
    x1, y1, z1, _ = p
    x2, y2, z2, _ = q
    return (x1 * z2 - x2 * z1) % P == 0 and (y1 * z2 - y2 * z1) % P == 0


def _recover_x(y: int, sign: int):
    if y >= P:
        return None
    x2 = (y * y - 1) * _inv(D * y * y + 1) % P
    if x2 == 0:
        return None if sign else 0
    x = pow(x2, (P + 3) // 8, P)
    if (x * x - x2) % P:
        x = x * SQRT_M1 % P
    if (x * x - x2) % P:
        return None
    if x & 1 != sign:
        x = P - x
    return x


def _decompress(b: bytes):
    if len(b) != 32:
        return None
    y = int.from_bytes(b, "little")
    sign = y >> 255
    y &= (1 << 255) - 1
    x = _recover_x(y, sign)
    if x is None:
        return None
    return (x, y, 1, x * y % P)


_GY = 4 * _inv(5) % P
G = (_recover_x(_GY, 0), _GY, 1, _recover_x(_GY, 0) * _GY % P)


def verify(public_key: bytes, msg: bytes, sig: bytes) -> bool:
    if len(public_key) != 32 or len(sig) != 64:
        return False
    a = _decompress(public_key)
    r = _decompress(sig[:32])
    if a is None or r is None:
        return False
    s = int.from_bytes(sig[32:], "little")
    if s >= L:
        return False
    k = int.from_bytes(hashlib.sha512(sig[:32] + public_key + msg).digest(), "little") % L
    return _equal(_mul(s, G), _add(r, _mul(k, a)))

ed25519_verify = verify

# ---- gpcanon/schema.py ---------------------------------------------------
"""gp-canon/1 sealed-zone schema (SCHEMA §3–4). Stdlib only.

validate_sealed(s) returns a list of (reason_code, detail); empty means valid.
"""

import re
from datetime import datetime


ID_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*(\.[a-z0-9][a-z0-9_-]*)+$")
HEX64 = re.compile(r"^[0-9a-f]{64}$")
HEX32 = re.compile(r"^[0-9a-f]{32}$")
HEX16 = re.compile(r"^[0-9a-f]{16}$")
DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")
VERSION = re.compile(r"^[A-Za-z0-9._+-]{1,64}$")
TS = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$")

KINDS = ("intent", "outcome", "failure", "seal", "finding")
DECISIONS = ("allow", "deny")
REASONS = ("policy_allowed", "policy_denied", "policy_unknown", "policy_raised",
           "policy_prefix_mismatch", "inputs_invalid")
RESULTS = ("ok", "raised", "skipped")
FAILURE_CODES = ("outcome_unwritten",)

COMMON = ("canon_version", "chain_id", "seq", "prev_hash", "kind", "recorded_at", "occurred_at")
GATED = ("gate_id", "actor", "detail")
FIELDS = {
    "intent": COMMON + GATED + ("policy_id", "subject", "action", "decision", "reason",
                                "policy_version", "policy_digest", "inputs_digest"),
    "outcome": COMMON + GATED + ("result",),
    "failure": COMMON + GATED + ("failure_code",),
    "seal": COMMON + ("key_id",),
    "finding": COMMON + ("actor", "subject", "finding_type", "claim", "evidence_digest", "detail"),
}
NULLABLE = {"detail", "policy_version", "policy_digest", "inputs_digest"}


def utc_ts(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def _ts_ok(v) -> bool:
    if not isinstance(v, str) or not TS.match(v):
        return False
    try:
        datetime.strptime(v, "%Y-%m-%dT%H:%M:%S.%fZ")   # rejects Feb 30, second 60
        return True
    except ValueError:
        return False


def _nonempty(v) -> bool:
    return isinstance(v, str) and v != ""


FORMAT = {
    "canon_version": lambda v: v == CANON_VERSION,
    "chain_id": lambda v: isinstance(v, str) and bool(ID_RE.match(v)),
    "seq": lambda v: isinstance(v, int) and not isinstance(v, bool) and v >= 0,
    "prev_hash": lambda v: isinstance(v, str) and bool(HEX64.match(v)),
    "kind": lambda v: v in KINDS,
    "recorded_at": _ts_ok,
    "occurred_at": _ts_ok,
    "gate_id": lambda v: isinstance(v, str) and bool(HEX32.match(v)),
    "policy_id": lambda v: isinstance(v, str) and bool(ID_RE.match(v)),
    "finding_type": lambda v: isinstance(v, str) and bool(ID_RE.match(v)),
    "evidence_digest": lambda v: isinstance(v, str) and bool(DIGEST.match(v)),
    "claim": _nonempty,
    "policy_version": lambda v: isinstance(v, str) and bool(VERSION.match(v)),
    "policy_digest": lambda v: isinstance(v, str) and bool(DIGEST.match(v)),
    "inputs_digest": lambda v: isinstance(v, str) and bool(DIGEST.match(v)),
    "subject": _nonempty,
    "action": _nonempty,
    "actor": _nonempty,
    "detail": lambda v: isinstance(v, str),
    "decision": lambda v: v in DECISIONS,
    "reason": lambda v: v in REASONS,
    "result": lambda v: v in RESULTS,
    "failure_code": lambda v: v in FAILURE_CODES,
    "key_id": lambda v: isinstance(v, str) and bool(HEX16.match(v)),
}


def validate_sealed(s) -> list[tuple[str, str]]:
    """Every SCHEMA reason code that applies, as (code, detail); [] means valid.

    Error semantics match ref/gp_canon.py and the schema vectors: an absent kind is
    missing_field, an unknown kind is bad_field, and canon_version_unsupported is
    collected alongside other errors rather than stopping the check.
    """
    if not isinstance(s, dict):
        return [("bad_field", "sealed zone is not an object")]
    kind = s.get("kind")
    if kind not in KINDS:
        return [("bad_field", f"kind={kind!r}")] if "kind" in s else [("missing_field", "kind")]
    errs = []
    if "canon_version" in s and s["canon_version"] != CANON_VERSION:
        errs.append(("canon_version_unsupported", repr(s["canon_version"])))
    want = FIELDS[kind]
    for f in want:
        if f not in s:
            errs.append(("missing_field", f))
    for f in s:
        if f not in want:
            errs.append(("unknown_field", f))
    for f in want:
        if f not in s or f == "canon_version":
            continue
        v = s[f]
        if v is None:
            if f not in NULLABLE:
                errs.append(("null_not_allowed", f))
            continue
        if not FORMAT[f](v):
            errs.append(("bad_field", f"{f}={v!r}"[:120]))
    if errs:
        return errs
    if kind == "finding":
        if s["finding_type"].split(".")[0] != s["chain_id"].split(".")[0]:
            errs.append(("type_prefix_mismatch", f"{s['finding_type']} on {s['chain_id']}"))
        return errs
    if kind != "intent":
        return errs

    # SCHEMA §4 intent rules
    reason, decision = s["reason"], s["decision"]
    if (decision == "allow") != (reason == "policy_allowed"):
        errs.append(("decision_reason_mismatch", f"{decision}/{reason}"))
    no_policy = reason in ("policy_unknown", "policy_prefix_mismatch")
    for f in ("policy_version", "policy_digest"):
        if no_policy and s[f] is not None:
            errs.append(("null_required", f))
        if not no_policy and s[f] is None:
            errs.append(("null_not_allowed", f))
    if (reason == "inputs_invalid") != (s["inputs_digest"] is None):
        errs.append(("null_required" if reason == "inputs_invalid" else "null_not_allowed", "inputs_digest"))
    consumer = s["chain_id"].split(".")[0]
    same = s["policy_id"].split(".")[0] == consumer
    if same == (reason == "policy_prefix_mismatch"):
        errs.append(("policy_prefix_mismatch", f"{s['policy_id']} on {s['chain_id']}"))
    return errs

# ---- gpcanon/verify.py ---------------------------------------------------
"""verify — offline verifier for gp-canon/1 chains. Stdlib only.

usage: python3 verify.py CHAIN_DIR [--pubkey HEX]... [--keyring FILE] [--allow-unpinned]
                         [--anchor FILE] [--policy POLICY_ID=PATH]... [--chain-id ID] [--json]

Exit codes (same meaning as gatepost/v1):
  0  verified; every seal checked against a pinned key (or --allow-unpinned given)
  1  chain broken: altered, deleted, reordered or spliced records; pairing violated;
     truncated against an anchor; policy file differs from the recorded digest
  2  signature failure: forged seal, sig missing on a seal or present on a non-seal
  3  malformed: not gp-canon/1 JSON, bad line keys, schema violation
  4  a seal is signed by a key that is not pinned, or outside that key's validity window

Keyring (key rotation): a JSON file {"keys": [{"key_id", "public_key_hex", "effective_from",
"retired_at"}]}, timestamps in the record format, retired_at may be null. A seal must be
made (recorded_at) inside its key's window. Get the keyring from somewhere the chain does
not control, the same as --pubkey.
  5  hashes and pairing check out but nothing is pinned: either no --pubkey was given
     (seals were not verified) or the chain has no seals at all (nothing is signed).
     Pin with --pubkey, using a key obtained from somewhere the chain does not control.

A pass proves the records were not changed after they were written and that each
gated action was recorded as decided. It does not prove the records are true.
Without --anchor, deletion of the tail (including its seals) is not detectable, and
the report says so.
"""

import hashlib
import json
import sys
from pathlib import Path


SEAL_DOMAIN = b"gatepost/seal/v1\n"

MALFORMED = {"float", "neg_zero", "int_range", "dup_key", "non_nfc", "lone_surrogate", "bad_json",
             "bad_type", "line_key_invalid", "missing_field", "unknown_field", "bad_field",
             "null_not_allowed", "null_required", "decision_reason_mismatch", "policy_prefix_mismatch",
             "canon_version_unsupported", "torn_line", "type_prefix_mismatch"}
CHAIN = {"seal_backdated", "hash_mismatch", "prev_mismatch", "seq_gap", "seq_duplicate", "chain_id_mismatch",
         "line_not_canonical", "unpaired", "pairing_invalid", "policy_digest_mismatch",
         "truncated_tail", "anchor_mismatch", "evidence_mismatch"}
SIGNATURE = {"sig_missing", "sig_forbidden", "bad_signature"}
KEY = {"key_id_mismatch", "key_outside_window"}
NOTICE = {"unsealed_tail", "tail_unanchored", "unpinned", "dangling_intent", "notes_unverified",
          "seals_unverified", "evidence_absent"}


class Report:
    def __init__(self):
        self.findings: list[dict] = []
        self.records = 0
        self.seals = 0
        self.last_seal_seq = None
        self.head = None

    def add(self, code: str, seq, detail: str = "") -> None:
        self.findings.append({"code": code, "seq": seq, "detail": detail})

    def codes(self) -> set[str]:
        return {f["code"] for f in self.findings}

    def exit_code(self) -> int:
        c = self.codes()
        for group, code in ((MALFORMED, 3), (CHAIN, 1), (SIGNATURE, 2), (KEY, 4)):
            if c & group:
                return code
        return 5 if "unpinned" in c else 0


def _lines(chain_dir: Path, rep: Report):
    segs = sorted(chain_dir.glob("seg-*.jsonl"))
    if not segs:
        rep.add("bad_json", None, "no segments")
    for seg in segs:
        data = seg.read_bytes()
        parts = data.split(b"\n")
        if parts and parts[-1] != b"":
            rep.add("torn_line", None, f"{seg.name}: final line has no newline (crash mid-write?)")
        for raw in parts[:-1]:
            yield seg.name, raw


def _check_evidence(chain_dir: Path, s: dict, rep: "Report") -> None:
    """A finding's evidence file, if the pack includes it, must hash to evidence_digest."""
    path = chain_dir / "evidence" / f"{s['evidence_digest'][7:]}.json"
    if not path.exists():
        rep.add("evidence_absent", s["seq"], "evidence file not in this pack; claim is bound but not inspectable")
        return
    data = path.read_bytes()
    if "sha256:" + hashlib.sha256(data).hexdigest() != s["evidence_digest"]:
        rep.add("evidence_mismatch", s["seq"], "evidence file does not match the digest in the record")
        return
    try:
        if canon(parse(data)) != data:
            rep.add("evidence_mismatch", s["seq"], "evidence file is not canonical")
    except CanonError as e:
        rep.add("evidence_mismatch", s["seq"], f"evidence file is not gp-canon/1 JSON: {e.reason}")


def load_keyring(path) -> tuple[dict[str, bytes], dict[str, tuple]]:
    """Parse a keyring file into (pubkeys, windows). Raises ValueError on any inconsistency."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    pubkeys, windows = {}, {}
    for k in data["keys"]:
        raw = bytes.fromhex(k["public_key_hex"])
        if len(raw) != 32:
            raise ValueError(f"keyring: {k.get('key_id')}: public key must be 32 bytes")
        kid = hashlib.sha256(raw).hexdigest()[:16]
        if kid != k["key_id"]:
            raise ValueError(f"keyring: key_id {k['key_id']} does not match its public key ({kid})")
        start, end = k.get("effective_from"), k.get("retired_at")
        for ts in (start, end):
            if ts is not None and not FORMAT["recorded_at"](ts):
                raise ValueError(f"keyring: {kid}: bad timestamp {ts!r}")
        pubkeys[kid] = raw
        windows[kid] = (start, end)
    return pubkeys, windows


def verify_chain(chain_dir, pubkeys: dict[str, bytes] | None = None, allow_unpinned: bool = False,
                 anchor: dict | None = None, policies: dict[str, str] | None = None,
                 chain_id: str | None = None, windows: dict[str, tuple] | None = None) -> Report:
    rep = Report()
    pubkeys = pubkeys or {}
    windows = windows or {}
    last_seal_at = None
    policy_digests = {}
    for pid, path in (policies or {}).items():
        policy_digests[pid] = "sha256:" + hashlib.sha256(Path(path).read_bytes()).hexdigest()

    expect_seq, prev = 0, GENESIS
    hashes: dict[int, str] = {}
    open_intent = None                  # (gate_id, decision, seq)
    for seg, raw in _lines(Path(chain_dir), rep):
        try:
            line = parse(raw)
        except CanonError as e:
            rep.add(e.reason, None, f"{seg}: {e}")
            continue
        if not isinstance(line, dict) or not {"h", "s"} <= set(line) or not set(line) <= {"h", "s", "n", "sig"}:
            rep.add("line_key_invalid", None, f"{seg}: keys {sorted(line) if isinstance(line, dict) else type(line).__name__}")
            continue
        s, h = line["s"], line["h"]
        seq = s.get("seq") if isinstance(s, dict) else None
        rep.records += 1
        errs = validate_sealed(s)
        for code, detail in errs:
            rep.add(code, seq, detail)
        if errs:
            continue
        if canon(line) != raw:
            rep.add("line_not_canonical", seq)
        if record_hash(s) != h:
            rep.add("hash_mismatch", seq, "record altered after it was written")
        if chain_id is None:
            chain_id = s["chain_id"]
        if s["chain_id"] != chain_id:
            rep.add("chain_id_mismatch", seq, f"{s['chain_id']} in chain {chain_id}")
        if seq in hashes:
            rep.add("seq_duplicate", seq)
        elif seq != expect_seq:
            rep.add("seq_gap", seq, f"expected {expect_seq}")
        if s["prev_hash"] != prev:
            rep.add("prev_mismatch", seq, "record deleted, inserted or reordered before this one")
        hashes[seq] = h
        prev, expect_seq = h, seq + 1
        if "n" in line:
            rep.add("notes_unverified", seq, "notes sit outside the hash")

        kind = s["kind"]
        if kind == "seal":
            if "sig" not in line:
                rep.add("sig_missing", seq)
            else:
                rep.seals += 1
                rep.last_seal_seq = seq
                sig = line["sig"]
                if not (isinstance(sig, str) and len(sig) == 128 and all(c in "0123456789abcdef" for c in sig)):
                    rep.add("bad_signature", seq, "sig is not 128 lowercase hex")
                elif pubkeys:
                    pub = pubkeys.get(s["key_id"])
                    if pub is None:
                        rep.add("key_id_mismatch", seq, f"sealed by {s['key_id']}, pinned {sorted(pubkeys)}")
                    elif not ed25519_verify(pub, SEAL_DOMAIN + canon(s), bytes.fromhex(sig)):
                        rep.add("bad_signature", seq, "seal signature does not verify")
                    else:
                        start, end = windows.get(s["key_id"], (None, None))
                        at = s["recorded_at"]           # fixed-width UTC strings compare in time order
                        if (start and at < start) or (end and at >= end):
                            rep.add("key_outside_window", seq,
                                    f"{s['key_id']} sealed at {at}, valid {start or '-'} to {end or 'now'}")
                if last_seal_at and s["recorded_at"] < last_seal_at:
                    rep.add("seal_backdated", seq, f"sealed at {s['recorded_at']}, before an earlier seal ({last_seal_at})")
                last_seal_at = max(last_seal_at or "", s["recorded_at"])
            if open_intent:
                rep.add("pairing_invalid", seq, "seal written while an intent was open")
        elif "sig" in line:
            rep.add("sig_forbidden", seq)

        if kind == "intent":
            if open_intent:
                rep.add("unpaired", open_intent[2], "intent has no outcome before the next intent")
            open_intent = (s["gate_id"], s["decision"], seq)
            pol = policy_digests.get(s["policy_id"])
            if pol and s["policy_digest"] is not None and s["policy_digest"] != pol:
                rep.add("policy_digest_mismatch", seq, f"{s['policy_id']}: recorded digest differs from given file")
        elif kind == "finding":
            if open_intent:
                rep.add("pairing_invalid", seq, "finding written while an intent was open")
            _check_evidence(Path(chain_dir), s, rep)
        elif kind in ("outcome", "failure"):
            if not open_intent or open_intent[0] != s["gate_id"]:
                rep.add("pairing_invalid", seq, f"{kind} without its intent")
            elif kind == "outcome":
                ok = {"allow": ("ok", "raised"), "deny": ("skipped",)}[open_intent[1]]
                if s["result"] not in ok:
                    rep.add("pairing_invalid", seq, f"{open_intent[1]} followed by result={s['result']}")
            open_intent = None

    last = expect_seq - 1
    rep.head = {"seq": last, "h": prev} if last >= 0 else None
    if open_intent:
        rep.add("dangling_intent", open_intent[2], "no outcome yet: action in progress or process died")
    if rep.last_seal_seq is None or rep.last_seal_seq < last:
        n = last - (rep.last_seal_seq if rep.last_seal_seq is not None else -1)
        if n > 0:
            rep.add("unsealed_tail", last, f"{n} record(s) after the last seal")
    if anchor:
        a_seq = anchor.get("seq")
        if anchor.get("chain_id") != chain_id:
            rep.add("anchor_mismatch", a_seq, "anchor is for another chain")
        elif a_seq not in hashes:
            rep.add("truncated_tail", a_seq, f"chain ends at seq {last}, anchor is at {a_seq}")
        elif hashes[a_seq] != anchor.get("h"):
            rep.add("anchor_mismatch", a_seq, "hash at the anchored seq differs")
    else:
        rep.add("tail_unanchored", last, f"truncation after seq {rep.last_seal_seq} not detectable")
    if rep.seals == 0 and not allow_unpinned:
        rep.add("unpinned", None, "no seals: nothing is signed, so the whole chain could be rewritten")
    elif rep.seals and not pubkeys and not allow_unpinned:
        rep.add("unpinned", None, "seals present but no --pubkey given: signatures NOT verified")
    elif not pubkeys or rep.seals == 0:
        rep.add("seals_unverified", None, "--allow-unpinned: integrity shown only against whoever can edit the files")
    return rep


def _summary(rep: Report, exit_code: int) -> str:
    verdict = {0: "OK", 1: "FAIL (chain)", 2: "FAIL (signature)", 3: "FAIL (malformed)",
               4: "FAIL (key)", 5: "NOT A PASS (unpinned)"}[exit_code]
    lines = [f"{verdict}: {rep.records} records, {rep.seals} seals, head "
             f"{rep.head['seq'] if rep.head else '-'}"]
    for f in rep.findings:
        mark = "·" if f["code"] in NOTICE else "✗"
        seq = f" seq {f['seq']}" if f["seq"] is not None else ""
        lines.append(f"  {mark} {f['code']}{seq}{': ' + f['detail'] if f['detail'] else ''}")
    return "\n".join(lines)


def main(argv=None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        return 3
    chain_dir, pubkeys, policies, anchor, chain_id, windows = None, {}, {}, None, None, {}
    allow_unpinned = as_json = False
    it = iter(args)
    try:
        for a in it:
            if a == "--pubkey":
                raw = bytes.fromhex(next(it))
                pubkeys[hashlib.sha256(raw).hexdigest()[:16]] = raw
            elif a == "--keyring":
                kp, kw = load_keyring(next(it))
                pubkeys.update(kp)
                windows.update(kw)
            elif a == "--allow-unpinned":
                allow_unpinned = True
            elif a == "--anchor":
                anchor = json.loads(Path(next(it)).read_text())
            elif a == "--policy":
                pid, path = next(it).split("=", 1)
                policies[pid] = path
            elif a == "--chain-id":
                chain_id = next(it)
            elif a == "--json":
                as_json = True
            elif chain_dir is None and not a.startswith("--"):
                chain_dir = a
            else:
                raise ValueError(f"unexpected argument {a!r}")
        if chain_dir is None:
            raise ValueError("CHAIN_DIR required")
        rep = verify_chain(chain_dir, pubkeys, allow_unpinned, anchor, policies, chain_id, windows)
    except (ValueError, StopIteration, OSError) as e:
        print(f"usage error: {e}", file=sys.stderr)
        return 3
    code = rep.exit_code()
    if as_json:
        print(json.dumps({"exit": code, "records": rep.records, "seals": rep.seals, "head": rep.head,
                          "findings": rep.findings}, ensure_ascii=False))
    else:
        print(_summary(rep, code))
    return code



if __name__ == "__main__":
    sys.exit(main())
